# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# If a build fails because these are out of date, check the current
# recommended numbers at https://fabricmc.net/develop and update them here.
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.9

# Mod Properties
mod_version=1.0.0
maven_group=com.donutbalance
archives_base_name=donut-balance

# Dependencies
fabric_version=0.102.0+1.21.1
